gateway:
  login-url: http://localhost:8080/login
  base-url: http://localhost:8080

app:
  endpoints:
    patient-service: http://patient-service:8081/patients
    notes-service: http://notes-service:8082/notes
    report-service: http://report-service:8083/report