gateway:
  login-url: http://gateway-service:8080/login

app:
  endpoints:
    patient-service: http://patient-service:8081/patients
    notes-service: http://notes-service:8082/notes
    report-service: http://report-service:8083/report