gateway:
  login-url: http://localhost:8080/login
  base-url: http://localhost:8080

app:
  endpoints:
    patient-service: ${gateway.base-url}/api/patients
    notes-service: ${gateway.base-url}/api/notes
    report-service: ${gateway.base-url}/api/report