gateway:
  login-url: http://localhost:8080/login

app:
  endpoints:
    patient-service: http://localhost:8081/patients
    notes-service: http://localhost:8082/notes
    report-service: http://localhost:8083/report