services :
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: patients_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
  gateway-service:
    build: ./gateway-service
    ports: 
    - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
    - frontend
    - patient-service
    - notes-service
    - report-service

  patient-service:
    build: ./patient-service
    ports: 
    - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
    - mysql

  notes-service:
    build: ./notes-service
    ports: 
    - "8082:8082"

  report-service:
    build: ./report-service
    ports: 
    - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
    - patient-service
    - notes-service

  frontend:
    build: ./frontend
    ports: 
    - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
    - patient-service
    - notes-service
    - report-service

volumes:
  mysql-data: