spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webmvc:
          routes:
          - id: patient-service
            uri: http://localhost:8081
            predicates:
              - Path=/patients/**
