spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: patient-service
            uri: http://localhost:8081
            predicates:
              - Path=/patients/**
          - id: notes-service
            uri: http://localhost:8082
            predicates:
              - Path=/notes/**
          - id: report-service
            uri: http://localhost:8083
            predicates:
              - Path=/report/**

